### ISSUE TITLE
テストケースの不一致による不具合

### ISSUE THREAD

**Issue by Mitarushi** [makutamoto/mojacoder#120]
## 不具合
inputとoutputでテストケースの不一致がある際、問題の編集やコードの提出で問題が発生しました。

## 経緯
まちがって次の問題を作っていまったところ、編集ができなくなり、ACコードを投げても内部エラーが出るようになりました。
https://mojacoder.app/users/Mitarushi/problems/problem
https://mojacoder.app/users/Mitarushi/problems/crime-counting

上の問題にはinputとoutputでテストケースの不一致があったので(special06-05.txt)、それを修正したのが次の問題が
https://mojacoder.app/users/Mitarushi/problems/crime-counting2
なのですが、ここでは不具合は生じませんでした。

**Comment by makutamoto** [comment]
対応遅れてすみません。
修正しました。
確認お願いして良いですか？

**Comment by Mitarushi** [comment]
大丈夫そうです
ありがとうございます
