### ISSUE TITLE
問題文や解説文、コンテストのトップページなどの Markdown のテキストに特定の文字列を含めるとエラーが発生する

### ISSUE THREAD

**Issue by naskya** [makutamoto/mojacoder#123]
問題文などに `$\texttt{\textbf{a}}$` や `$\textbf{\texttt{a}}$` という文字列を含めると、直ちにページ画面が以下のようになって操作できなくなります（`a` の部分は空でない他の文字列に変えても同様です）。

![Screenshot from 2022-05-20 23-57-16](https://user-images.githubusercontent.com/48414671/169556651-bd9751fc-f489-4653-9a00-8b7ba6aa78d2.png)
問題に対してこの文字列を含むコメントを投稿されるとコメント欄が開けなくなります。また、問題文にこの文字列を含む問題を zip ファイルで投稿すると表示も削除もできない問題が生まれてしまうと予想されます（未検証）。

`texttt` と `textbf` 以外の組み合わせでも落ちるパターンはあるかもしれませんが、適当に探した限りでは他の組み合わせは見つかりませんでした（例えば `$\mathbf{\texttt{a}}$` や `$\textrm{\texttt{a}}$` とすると `$\texttt{a}$` としたときと同じものがレンダリングされ、落ちることはありませんでした）。

**Comment by makutamoto** [comment]
問題報告ありがとうございます。当方編入学試験を控えておりまして、対応が9月以降になりそうなのですが、大丈夫ですか？

**Comment by naskya** [comment]
全く問題ありません。というか正直返信が返ってくることすら全く期待していませんでした（失礼な発言ですみません）。

久しぶりに @makutamoto さんが浮上しているところが見られて大変嬉しいです。試験頑張ってください！
