### ISSUE TITLE
Twitterに共有したときのバグ

### ISSUE THREAD

**Issue by Raclamusi** [makutamoto/mojacoder#78]
URLに`/ja`がついているときだけ、Twitterのカードのタイトルが"undefined"になります。
![twitter_screen](https://user-images.githubusercontent.com/61970673/103327141-be1c2f00-4a96-11eb-8e78-1f1cc79d9237.jpg)

`/en`や言語コードをつけないときは、正しく問題名が表示されました。
また、LINEでは正しく表示されました。
![line_screen](https://user-images.githubusercontent.com/61970673/103327074-68e01d80-4a96-11eb-9072-f968aabef33d.jpg)

**Comment by makutamoto** [comment]
Issue立てありがとうございます！
ツイートボタンから共有できるリンクと現在のページのリンクを一致させることで対応しました。
