### ISSUE TITLE
提出コードにシングルクォーテーションが含まれていると正しく提出できないバグ

### ISSUE THREAD

**Issue by Raclamusi** [makutamoto/mojacoder#90]
## 内容

シングルクォーテーション`'`が含まれたコードを提出すると、「`\'`は認識できません」という感じのエラーが出て、提出はずっと **`WJ`** でぐるぐるしています。

すべての言語で発生します。また、Playgroundにおいても発生します。

## スクリーンショット

問題ページとコンソール
<img width="948" alt="シングルクォーテーションがつかえへんやん" src="https://user-images.githubusercontent.com/61970673/103563347-f9d45000-4eff-11eb-9c4b-fc985ee78dd8.png">

提出詳細ページ
<img width="946" alt="提出詳細画面" src="https://user-images.githubusercontent.com/61970673/103564926-b8916f80-4f02-11eb-9519-4d64c09502e3.png">

**Comment by makutamoto** [comment]
完了
